### ISSUE TITLE
NTF Custom Roles don't spawn and person doesn't get a custom role if the role was already given in a previous round.

### ISSUE THREAD

**Issue by kadotcom** [FoxWorn3365/UncomplicatedCustomRoles#3]
Hello, I keep on having these two issues with the plugin. First issue isn't just an issue I am getting, but an issue others are getting. When NTF spawn, even if the role is set to 100% chance of spawning, the NTF doesn't get the role. This is an example of the role config I'm using.

```
  - id: 22
    name: 'Suppressor'
    custom_info: 'Suppressor'
    spawn_condition: RespawnWave
    max_players: 1
    min_players: 1
    spawn_chance: 100
    role: NtfPrivate
    role_appearance: ClassD
    can_replace_roles:
    - NtfPrivate
    health: 80
    max_health: 80
    ahp: 0
    hume_shield: 0
    movement_boost: 0
    effects: []
    scale:
      x: 0
      y: 0
      z: 0
    spawn_broadcast: |-
      <b>You have spawned as</b> <color=#7ec6fe><b>Nine-Tailed Fox:</b></color> <color=#5fadfa><b>Suppressor</b></color>
      <i>Speed and stun, a perfect combo.</i><br><i>You go slightly faster than other MTF, have infinite sprint,</i><br><i>and have a tranq gun.</i>.
    spawn_broadcast_duration: 10
    inventory:
    - GunShotgun
    - KeycardMTFOperative
    - Medkit
    - GrenadeFlash
    - Radio
    - ArmorCombat
    custom_items_inventory:
    - 26
    ammo:
      Nato9: 60
      Ammo12Gauge: 24
    spawn: KeepRoleSpawn
    spawn_zones: []
    spawn_rooms: []
    spawn_position:
      x: 0
      y: 0
      z: 0
    spawn_offset:
      x: 0
      y: 0
      z: 0
    ignore_spawn_system: false
```

Another issue is that if a player gets one custom role during one round, for every other round until the server restarts, that same role will not be given at all. To my knowledge no one else has mentioned this bug so I don't know if it's just a thing on my end, or not.
