### ISSUE TITLE
"Can Escape" & "Role Appearence" Doesn't work

### ISSUE THREAD

**Issue by theowllusev** [FoxWorn3365/UncomplicatedCustomRoles#4]
Hello, i have two issues, one of that is when i write the subclass to "Can escape: true" that actually don't work, equal to the role appearence, i give another appearence to a scientist's subclass and do not work

```
guardia_l_c_z:
  - id: 3
    name: 'Guardia LCZ'
    custom_info: 'Escapa de las instalaciones.'
    spawn_condition: RoundStart
    max_players: 1
    min_players: 1

    spawn_chance: 10
    role: Scientist
    role_appearance: FacilityGuard
    can_replace_roles:
    - Scientist
    health: 100
    max_health: 100
    ahp: 0
    hume_shield: 0
    movement_boost: 0
    effects: []
    can_escape: true
    scale:
      x: 0
      y: 0
      z: 0
    spawn_broadcast: |-
      <b>ERES UN <color=#B5B2B2>GUARDIA</color> DE <color=yellow>LCZ</color>!<b>
      Sobrevivir abajo no es facil, asi que cuida a tus compañeros
    spawn_broadcast_duration: 5
    inventory:
    - KeycardScientist
    - Medkit
    - GunCOM18
    custom_items_inventory: []
    ammo:
      Nato9: 40
    spawn: KeepRoleSpawn
    spawn_zones: []
    spawn_rooms: []
    spawn_position:
      x: 0
      y: 0
      z: 0
    spawn_offset:
      x: 0
      y: 0
      z: 0
    ignore_spawn_system: false
    
    guardia_escapista:
  - id: 12
    name: 'Guardia Escapista'
    custom_info: 'Escapa y Protege las instalaciones.'
    spawn_condition: RoundStart
    max_players: 1
    min_players: 1
    spawn_chance: 10
    role: FacilityGuard
    role_appearance: FacilityGuard
    can_replace_roles:
    - FacilityGuard
    health: 100
    max_health: 100
    ahp: 0
    hume_shield: 0
    movement_boost: 0
    effects: []
    can_escape: false
    scale:
      x: 0
      y: 0
      z: 0
    spawn_broadcast: |-
      <b> ERES UN <color=#B3B2B2>GUARDIA ESCAPISTA</color></b>
      Estas preparado para huir, no pierdas el tiempo!.
    spawn_broadcast_duration: 5
    inventory:
    - KeycardMTFOperative
    - GunCrossvec
    - Medkit
    - Adrenaline
    - ArmorLight
    - Radio
    custom_items_inventory: []
    ammo:
      Nato9: 60
    spawn: RoomsSpawn
    spawn_zones: []
    spawn_rooms:
    - HczArmory
    spawn_position:
      x: 0
      y: 0
      z: 0
    spawn_offset:
      x: 0
      y: 0
      z: 0
    ignore_spawn_system: false
```
